@Library(['Prov_devops_Library@master']) _

def sberchatReport(status, text) {
    def data = [
    'peer': 'ca8416a4b5ff11ee',
    'status': status,
    'text': text.bytes.encodeBase64().toString(),
    'url': "${BUILD_URL}"
    ]
    String json = writeJSON returnText: true, json: data
    httpRequest httpMode: 'POST',  url: "https://sbt-qa-jenkins.delta.sbrf.ru/sberchatbot", requestBody:  json
}

pipeline {
    agent {
        node {
            label 'masterLin'
        }
    }

    parameters {
        string(name: 'DISTR_NAME', defaultValue: 'Change Me 01.***.1-1', description: "Версия дистрибутива, именно в таком формате 01.***.1-1")
        // mavenMetadataVersions (
        //     artifactId: "CI05327816",
        //     classifier: '',
        //     credentialsId: 'maven_artifact_list_cred_secret',
        //     currentArtifactInfoLabel: '',
        //     currentArtifactInfoPattern: '',
        //     currentArtifactInfoUrl: '',
        //     defaultValue: '',
        //     description: 'Выбор версии дистрибутива',
        //     groupId: "CI00377836",
        //     maxVersions: '160',
        //     name: 'DISTR_NAME',
        //     packaging: 'zip',
        //     repoBaseUrl: 'https://nexus-ci.delta.sbrf.ru/repository/maven-distr',
        //     sortOrder: 'DESC',
        //     versionFilter: ''
        // )
        choice(name: 'DEST_HOST', choices: ['10.55.55.230', '10.53.247.213', '10.141.17.78', '10.141.17.132'], description: "IP адрес хоста деплоя")
        booleanParam(name: 'SberChat', defaultValue: true, description: 'Отправить уведомление')
        booleanParam(name: 'Deploy_to_Autotest', defaultValue: true, description: 'Деплой на Autotest (при успешном выполнении джобы)')
        booleanParam(name: 'Deploy_to_DEV_SVPL', defaultValue: true, description: 'Деплой на DEV_SVPL (при успешном выполнении джобы)')
    }
    
    options {
        ansiColor('xterm')
    }
    
    environment {
        NODEJS_HOME = tool name: "node-22.5.1", type: 'nodejs'
    }

    stages {

        // stage('Get distr_name') {
        //     steps {
        //        script {
        //         println("Get prj name")
        //             DISTR_NAME = DISTR_NAME_VERSION.split("_")[0].split("D-")[1]
        //             echo "Show distr name: ${DISTR_NAME}"          
        //        }
        //     }
        // }
        // Такая всратая конструкция получения имени проекта, по причине того, что длинна пути на разных нодах отличается. Разворачиваем строку, берем перввый каталог и ревертим обратно.
        stage('Get project name') {
            steps {
               script {
                println("Get prj name")
                    PRJ_NAME = sh (
                        script: 'pwd',
                        returnStdout: true
                    )reverse().split("/")[0].reverse().trim()
                    echo "Show project name: ${PRJ_NAME}"          
               }
            }
        }

        stage('Determine version') {
            steps {
                script {
                        currentBuild.displayName = "${DISTR_NAME}"
                }
            }
        }

        stage('Load prj param') {
          steps {
            load "./$PRJ_NAME/prjparam.groovy"
          }
        }

        stage('Nexus CD Download') {
            steps {
                script {
                    withCredentials([usernamePassword(
                            credentialsId: "${NEXUS_CREDENTIAL_ID}",
                            usernameVariable: 'USER',
                            passwordVariable: 'PWD')]) {
                        def distrib_url = "${NEXUS_URL}/repository/" +
                                "${NEXUS_CD_REPOSITORY}/" +
                                "${NEXUS_GROUP_ID}/" +
                                "${NEXUS_ARTIFACT_ID}/" +
                                "D-${DISTR_NAME}_${PRJ_NAME}/" +
                                "${NEXUS_ARTIFACT_ID}-D-${DISTR_NAME}_${PRJ_NAME}-distrib.zip"
                        sh "curl -v -u '${USER}@${DOMEN_PREFIX}:${PWD}' -o distrib.zip ${distrib_url}"
                        currentBuild.description = """ Nexus ver: <a href="${distrib_url}">${DISTR_NAME}</a> """
                        sh "unzip distrib.zip"
                        sh "ls -la build"
                    }
                }
            }
        }

        stage('Deploy: copy files') {
            steps {
                sshagent(['TYZ_SSH']) {
                sh """
                ssh -o StrictHostKeyChecking=no -l ${SSH_USER} ${DEST_HOST} sudo -u $LOCAL_USER mkdir -p /opt/provisioning/$PRJ_NAME/{env,bin,log,tmp}
                ssh -o StrictHostKeyChecking=no -l ${SSH_USER} ${DEST_HOST} sudo -u $LOCAL_USER mv /opt/provisioning/$PRJ_NAME/build /opt/provisioning/$PRJ_NAME/build_`date +"%Y%m%d_%H%M"` | true
                ssh -o StrictHostKeyChecking=no -l ${SSH_USER} ${DEST_HOST} sudo -u $LOCAL_USER chmod 777 -R /opt/provisioning/$PRJ_NAME
                scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./build ${SSH_USER}@${DEST_HOST}:/opt/provisioning/$PRJ_NAME/  
                ssh -o StrictHostKeyChecking=no -l ${SSH_USER} ${DEST_HOST} sudo -u $LOCAL_USER sudo /usr/bin/chown -R $LOCAL_USER:$LOCAL_USER /opt/provisioning
                ssh -o StrictHostKeyChecking=no -l ${SSH_USER} ${DEST_HOST} sudo -u $LOCAL_USER chmod 755 -R /opt/provisioning/$PRJ_NAME          
                """
                }
            }
        }

        stage('Deploy: custom task') {
            steps {
                load "./$PRJ_NAME/custom_task.groovy"
            }
        } 

        stage('Confluence: set version') {
            steps {
                dir('helpers') {
                    script {
                        setConfluenceVersion("${env.NODEJS_HOME}", "IFT", "${PRJ_NAME}", "${DISTR_NAME}", "${NEXUS_ARTIFACT_ID}")
                        manager.createSummary('notepad.png').appendText('<b><a href="https://confluence.sberbank.ru/pages/viewpage.action?pageId=18142367984">Автоматическая таблица версий Provisioning</a></b>')
                    }
                }
            }
        }
    }
    
    post {
        success {
            script {
               if (params.SberChat) {
                 BUILD_TRIGGER_BY = currentBuild.getBuildCauses()[0].shortDescription + " / " + currentBuild.getBuildCauses()[0].userId
                 sberchatReport('OK', "DEPLOY - IFT\n${PRJ_NAME}\nVer: ${DISTR_NAME}\nDest srv IP: ${DEST_HOST}\n${BUILD_TRIGGER_BY}\nПродолжительность деплоя: ${currentBuild.durationString.replace(' and counting', '')}")
               } 
            }
            script {
                if (params.Deploy_to_Autotest) { 
                   build job: "../Provisioning_CDL_Autotest/${PRJ_NAME}/", 
                   parameters: [
                     string(name: 'DISTR_NAME', value:  "${DISTR_NAME}"),
                     string(name: 'SberChat', value:  "${SberChat}")
                   ],
                   wait: false
                }

                if (params.Deploy_to_DEV_SVPL) { 
                   build job: "../Provisioning_CDL_SVPL/${PRJ_NAME}/", 
                   parameters: [
                     string(name: 'DISTR_NAME', value:  "${DISTR_NAME}"),
                     string(name: 'SberChat', value:  "${SberChat}")
                   ],
                   wait: false
                }
            }
        }
        always {
            println "This is the end"
            cleanWs disableDeferredWipeout: true, deleteDirs: true //Очистка workspace Подробнее https://jenkins.io/doc/pipeline/steps/ws-cleanup/
            }
    }
}
